version: "3.5"
services:
  api:
    image: keymetrics/pm2:14-slim
    working_dir: /app
    volumes:
      - ./server:/app
    ports:
      - "${API_SERVER_EXPOSE_PORT}:80"
    environment:
      - TZ=Asia/Shanghai
    command: [ "pm2-runtime", "api.yml" ]
    restart: on-failure

  daemon:
    image: keymetrics/pm2:14-slim
    working_dir: /app
    volumes:
      - ./server:/app
    environment:
      - TZ=Asia/Shanghai
    command: [ "pm2-runtime", "daemon.yml" ]
