version: "3.5"
services:
  api:
    image: keymetrics/pm2:14-slim
    working_dir: /app
    volumes:
      - ./server:/app
    ports:
      - "${API_SERVER_EXPOSE_PORT}:80"
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_USERNAME=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: [ "pm2-runtime", "api.yml" ]
    restart: on-failure

  daemon:
    image: keymetrics/pm2:14-slim
    working_dir: /app
    volumes:
      - ./server:/app
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_USERNAME=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: [ "pm2-runtime", "daemon.yml" ]
