import mysql from '@common/dbs/mysql';

import { AdminModel } from './admin.model';
import { AdminSessionModel } from './admin_session.model';
import { AdminAllowIpModel } from './admin_allow_ip.model';
import { UserModel } from './user.model';
import { UserAuthModel } from './user_auth.model';
import { UserSessionModel } from './user_session.model';
import { UserWalletModel } from './user_wallet.model';
import { UserRechargeModel } from './user_recharge.model';
import { UserWithdrawModel } from './user_withdraw.model';
import { UserStatisticModel } from './user_statistic.model';
import { UserQueueModel } from './user_queue.model';
import { OrderModel } from './order.model';
import { CardModel } from './card.model';
import { CardStatisticModel } from './card_statistic.model';
import { MerchantModel } from './merchant.model';
import { AgentModel } from './agent.model';
import { ConfigModel } from './config.model';
import { P2pOrderModel } from './p2p_order.model';
import { UserLockModel } from './user_lock.model';
import { LevelModel } from './level.model';
import { AgentWithdrawModel } from './agent_withdraw.model';
import { MerchantWithdrawModel } from './merchant_withdraw.model';
import { StatisticModel } from './statistic.model';
import { UserLogModel } from './user_log.model';
import { MerchantLogModel } from './merchant_log.model';
import { AdminLogModel } from './admin_log.model';

export const adminRepository = mysql.getRepository(AdminModel);
export const adminSessionRepository = mysql.getRepository(AdminSessionModel);
export const adminAllowIpRepository = mysql.getRepository(AdminAllowIpModel);
export const userRepository = mysql.getRepository(UserModel);
export const userAuthRepository = mysql.getRepository(UserAuthModel);
export const userSessionRepository = mysql.getRepository(UserSessionModel);
export const userWalletRepository = mysql.getRepository(UserWalletModel);
export const userRechargeRepository = mysql.getRepository(UserRechargeModel);
export const userWithdrawRepository = mysql.getRepository(UserWithdrawModel);
export const userStatisticRepository = mysql.getRepository(UserStatisticModel);
export const orderRepository = mysql.getRepository(OrderModel);
export const cardRepository = mysql.getRepository(CardModel);
export const cardStatisticRepository = mysql.getRepository(CardStatisticModel);
export const merchantRepository = mysql.getRepository(MerchantModel);
export const configRepository = mysql.getRepository(ConfigModel);
export const userQueueRepository = mysql.getRepository(UserQueueModel);
export const p2pOrderRepository = mysql.getRepository(P2pOrderModel);
export const userLockRepository = mysql.getRepository(UserLockModel);
export const levelRepository = mysql.getRepository(LevelModel);
export const agentRepository = mysql.getRepository(AgentModel);
export const agentWithdrawRepository = mysql.getRepository(AgentWithdrawModel);
export const merchantWithdrawRepository = mysql.getRepository(MerchantWithdrawModel);
export const statisticRepository = mysql.getRepository(StatisticModel);
export const userLogRepository = mysql.getRepository(UserLogModel);
export const merchantLogRepository = mysql.getRepository(MerchantLogModel);
export const adminLogRepository = mysql.getRepository(AdminLogModel);